assert response 200

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,16 +1,20 @@
 on:
   issues:
-    types: [opened, edited]
+    types: [opened]
 
 jobs:
   sendRequest:
     runs-on: ubuntu-latest
     steps:
       - name: Send Issue to withmeaning
-        run: >
-          curl -X POST 'https://spile.withmeaning.io/add_item' -H 'Content-Type: application/json' -H 'auth_token: ${{ secrets.AUTH_TOKEN }}' -d '{
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST 'https://spile.withmeaning.io/add_item' -H 'Content-Type: application/json' -H 'auth_token: ${{ secrets.AUTH_TOKEN }}' -d '{
             "title": "${{ github.event.issue.title }}",
             "content": "${{ github.event.issue.body }}",
             "link": "${{ github.event.repository.html_url }}",
             "author": "${{ github.event.issue.user.login }}",
-            "type": "do"}'
+            "type": "do"}')
+          if [ "$response" -ne 200 ]; then
+            echo "API request failed with HTTP status $response"
+            exit 1
+          fi
